version: "3"

services:
  valheim:
    image: valheim_server:alpha
    container_name: valheim_server
    restart: always
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - SERVER_NAME=Drezaels TestServer
      - WORLD_NAME=DrezaelsWorld
      - PUBLIC=true
      - AUTOUPDATE=false
      - GAME_MODE=bepinex
      - ./server:/valheim-server/server
      - ./save:/valheim-server/save