version: "3"

services:
  valheim:
    image: valheim_server:alpha
    container_name: valheim_server
    restart: always
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - SERVER_NAME=Drezaels TestServer
      - WORLD_NAME=DrezaelsWorld
      - PUBLIC=true
      - AUTOUPDATE=false
      - GAME_MODE=bepinex
      - MODS=
          https://gcdn.thunderstore.io/live/repository/packages/Zinal001-Server_Messages-1.0.1.zip,
          https://gcdn.thunderstore.io/live/repository/packages/ValheimAddicts-Compass_By_Aedenthorn-0.8.2.zip

    volumes:
      - ./server:/valheim-server/server
      - ./save:/valheim-server/save